#!/usr/bin/env node
// Regenerates curated.txt, the curated tier: the entries hermes-hq/hodios-dist ships as Agent Skills, Claude Code
// plugins, native trees, paste files and bundles. Every entry, curated or not, is in the catalog, so
// `hodios search` and `hodios install`, the site and Hermes IDE reach all of them. Rule: TAXONOMY.md §6.1.
//
// Usage: npm run build && node tools/release/curate.mjs [--target N] [--check]
//   --target N  fill to N entries (default 1,900; the cap is 2,000)
//   --check     exit 1 if curated.txt would change instead of writing it
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const TARGET = 1900;
export const MAX = 2000;
const STATUS_RANK = { stable: 2, experimental: 1, incubating: 0, deprecated: -1 };
/** Code-unit order, the order curated.txt and ids.lock are checked in (not locale order). */
const order = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

export const HEADER = `# curated.txt: the curated tier, one id per line, sorted. Regenerated by tools/release/curate.mjs; review the diff.
# Only curated entries go to hermes-hq/hodios-dist (Agent Skills, Claude Code and Copilot plugins, native trees,
# paste files, bundles), which holds at most 2,000. Every entry in every tier is in catalog/v1, so the hodios CLI,
# the site and Hermes IDE reach the rest. The rule (TAXONOMY.md §6.1):
#   1. An id stays once listed, unless it is deprecated, moves to other/unsorted or is opted out. A renamed id is
#      replaced by its successor. Entries never churn in and out between releases.
#   2. Every new persona, workflow, rule and style is added.
#   3. New prompts fill the list up to 1,900, picked one at a time: first the domain furthest below its quota
#      (the domain's share of the library times 1,900), then the category with the fewest curated entries, then
#      status (stable, experimental, incubating), eval cases, examples, and finally the id.
#   Never added automatically: other/unsorted, deprecated entries, and entries with advice_risk (medical,
#   mental-health, legal, financial), which need a reviewer from the domain's CODEOWNERS group; add those by hand.
# Hand edits: add an id to curate it; write !<id> to opt an entry out (it leaves the tier and is never re-added).
# The first list kept every entry of catalog 2026.1003.0, the last release that shipped the whole library.
`;

/**
 * @typedef {{id: string, kind: string, domain: string, category: string, status: string, advice: boolean,
 *   aliases: string[], evalCases: number, examples: boolean}} Candidate
 * @param {Candidate[]} entries every live entry
 * @param {{listed: Iterable<string>, excluded?: Iterable<string>, target?: number, max?: number}} opts
 * @returns {{ids: string[], added: string[], dropped: string[]}}
 */
export function selectCurated(entries, { listed, excluded = [], target = TARGET, max = MAX }) {
  const out = new Set(excluded);
  const byId = new Map(entries.map((e) => [e.id, e]));
  const aliasOf = new Map(entries.flatMap((e) => e.aliases.map((a) => [a, e.id])));
  const eligible = (e) => e.status !== 'deprecated' && e.category !== 'unsorted' && !out.has(e.id);

  const keep = new Set();
  const dropped = [];
  for (const id of listed) {
    const entry = byId.get(id) ?? byId.get(aliasOf.get(id) ?? '');
    if (entry && eligible(entry)) keep.add(entry.id);
    else dropped.push(id);
  }
  const before = new Set(keep);
  const pool = entries.filter((e) => eligible(e) && !e.advice && !keep.has(e.id)).sort((a, b) => order(a.id, b.id));
  for (const e of pool) if (e.kind !== 'prompt') keep.add(e.id);
  if (keep.size > max) throw new Error(`${keep.size} curated entries before any prompt; the cap is ${max}`);

  // Domain quotas: the domain's share of the library, by largest remainder so they sum to the target.
  const live = entries.filter((e) => e.status !== 'deprecated' && e.category !== 'unsorted');
  const size = new Map();
  for (const e of live) size.set(e.domain, (size.get(e.domain) ?? 0) + 1);
  const quota = new Map();
  const shares = [...size].map(([d, n]) => ({ d, exact: (target * n) / live.length }));
  for (const s of shares) quota.set(s.d, Math.floor(s.exact));
  let left = target - [...quota.values()].reduce((a, b) => a + b, 0);
  for (const s of [...shares].sort(
    (a, b) => b.exact - Math.floor(b.exact) - (a.exact - Math.floor(a.exact)) || order(a.d, b.d),
  )) {
    if (left-- <= 0) break;
    quota.set(s.d, (quota.get(s.d) ?? 0) + 1);
  }

  const inDomain = new Map();
  const inCategory = new Map();
  const count = (e) => {
    inDomain.set(e.domain, (inDomain.get(e.domain) ?? 0) + 1);
    inCategory.set(e.category, (inCategory.get(e.category) ?? 0) + 1);
  };
  for (const id of keep) count(byId.get(id));
  const prompts = pool.filter((e) => e.kind === 'prompt');
  const better = (a, b) =>
    (quota.get(b.domain) ?? 0) -
      (inDomain.get(b.domain) ?? 0) -
      ((quota.get(a.domain) ?? 0) - (inDomain.get(a.domain) ?? 0)) ||
    (inCategory.get(a.category) ?? 0) - (inCategory.get(b.category) ?? 0) ||
    STATUS_RANK[b.status] - STATUS_RANK[a.status] ||
    b.evalCases - a.evalCases ||
    Number(b.examples) - Number(a.examples) ||
    order(a.id, b.id);
  while (keep.size < Math.min(target, max) && prompts.length > 0) {
    let best = 0;
    for (let i = 1; i < prompts.length; i++) if (better(prompts[i], prompts[best]) < 0) best = i;
    const [pick] = prompts.splice(best, 1);
    keep.add(pick.id);
    count(pick);
  }
  const ids = [...keep].sort(order);
  return { ids, added: ids.filter((id) => !before.has(id)), dropped };
}

/** curated.txt text: the header, then curated ids and `!` opt-outs in one sorted list. */
export function renderList(ids, excluded = []) {
  const lines = [...ids.map((id) => ({ id, line: id })), ...[...excluded].map((id) => ({ id, line: `!${id}` }))];
  lines.sort((a, b) => order(a.id, b.id));
  return `${HEADER}${lines.map((l) => l.line).join('\n')}\n`;
}

async function main() {
  const root = fileURLToPath(new URL('../../', import.meta.url));
  const { loadRepo } = await import(pathToFileURL(join(root, 'packages/cli/dist/load.js')).href);
  const { checkLibrary, parseCuratedList, parseYamlDocument } = await import('@hermes-hq/hodios-core');
  const repo = loadRepo(root);
  const list = repo.context.curated ?? parseCuratedList('');
  // Check without curated.txt, so a stale list (a deprecated or moved id) can still be regenerated.
  const checked = checkLibrary(repo.sources, { ...repo.context, curated: undefined });
  const errors = [...repo.issues, ...checked.issues].filter((i) => i.severity === 'error');
  if (errors.length > 0) throw new Error(`${errors.length} validation errors; run npm run validate`);
  const domainOf = (category) => repo.context.vocab.get('category')?.meta.get(category)?.domain ?? 'other';
  const files = new Map(repo.sources.map((s) => [s.dir, s.files]));
  const entries = checked.entries
    .filter((e) => e.frontmatter)
    .map(({ dir, frontmatter: fm }) => {
      const folder = files.get(dir) ?? new Map();
      const evals = folder.has('evals.yaml') ? parseYamlDocument(folder.get('evals.yaml')).data : undefined;
      return {
        id: fm.id,
        kind: fm.kind,
        domain: domainOf(fm.category),
        category: fm.category,
        status: fm.status,
        advice: (fm.advice_risk ?? []).length > 0,
        aliases: fm.aliases ?? [],
        evalCases: Array.isArray(evals?.cases) ? evals.cases.length : 0,
        examples: [...folder.keys()].some((f) => f.startsWith('examples/')),
      };
    });
  const at = process.argv.indexOf('--target');
  const target = at > 0 ? Number(process.argv[at + 1]) : TARGET;
  if (!Number.isInteger(target) || target < 0 || target > MAX) throw new Error(`--target must be 0-${MAX}`);
  const result = selectCurated(entries, { listed: list.ids, excluded: list.excluded, target });
  const file = join(root, 'curated.txt');
  let before = '';
  try {
    before = readFileSync(file, 'utf8');
  } catch {
    // first run
  }
  const after = renderList(result.ids, list.excluded);
  if (process.argv.includes('--check')) {
    if (before !== after) {
      console.error('curated.txt is out of date; run node tools/release/curate.mjs and review the diff');
      process.exit(1);
    }
    return;
  }
  writeFileSync(file, after);
  console.log(
    `curated.txt: ${result.ids.length} of ${entries.length} entries curated (+${result.added.length}, -${result.dropped.length}).`,
  );
  if (result.dropped.length > 0) console.log(`Left the tier: ${result.dropped.join(', ')}`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) await main();
